spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/academia?useTimezone=true&serverTimezone=UTL&useLegacyData
    username: postgres
    password: master
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.format_sql: true




